# Generated by Django 3.2.9 on 2021-12-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211229_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
