# Generated by Django 3.2.9 on 2021-12-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente', models.CharField(max_length=10)),
                ('secretario', models.CharField(max_length=10)),
                ('p_guia', models.CharField(max_length=10)),
                ('v_feu', models.CharField(max_length=10)),
                ('otros', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=8)),
                ('hora', models.CharField(max_length=5)),
                ('area', models.CharField(max_length=150)),
                ('usuario_d', models.CharField(max_length=10)),
                ('valida', models.BooleanField(default=False)),
                ('asignada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('anno_ac', models.CharField(max_length=9)),
                ('fecha', models.CharField(max_length=8)),
                ('grupo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('rol', models.CharField(max_length=20)),
                ('permisos', models.CharField(max_length=1)),
            ],
        ),
    ]
