# Generated by Django 3.2.9 on 2021-12-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comision_denuncia_expediente_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.AddField(
            model_name='comision',
            name='dias_utiles',
            field=models.IntegerField(default=30),
        ),
    ]
