# Generated by Django 3.2.9 on 2021-12-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211230_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='valida',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='asignada',
            field=models.CharField(default='No', max_length=2),
        ),
    ]
