# Generated by Django 3.2.9 on 2021-12-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211230_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=9),
        ),
    ]
