# Generated by Django 3.2.9 on 2021-12-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_denuncia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(max_length=9),
        ),
    ]
