# Generated by Django 3.2.9 on 2021-12-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_denuncia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.BooleanField(default='Pendiente', max_length=9),
        ),
    ]
