# Generated by Django 3.2.9 on 2021-12-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211230_1443'),
    ]

    operations = [
     
    ]
