# Generated by Django 3.2.9 on 2021-12-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_denuncia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='core.usuario'),
        ),
    ]
