# Generated by Django 3.2.9 on 2022-01-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220103_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='password',
        ),
    ]
