# Generated by Django 3.2.9 on 2022-01-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_perfil_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cat_d',
            field=models.CharField(choices=[('1', '-----'), ('2', 'Titular'), ('3', 'Adiestrado'), ('4', 'Instructor')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('1', '-----'), ('2', 'Profesor'), ('3', 'J. Apto'), ('4', 'J. Asig')], default='1', max_length=8),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('1', 'Usuario'), ('2', 'Admin')], default='1', max_length=7),
        ),
    ]
