# Generated by Django 3.2.9 on 2022-01-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220103_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='un_pass',
            field=models.CharField(default='', max_length=30),
        ),
    ]
