# Generated by Django 3.2.9 on 2022-01-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220103_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('-----', '-----'), ('Profesor', 'Profesor'), ('J. Apto', 'J. Apto'), ('J. Asig', 'J. Asig')], default='-----', max_length=8),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cat_d',
            field=models.CharField(choices=[('-----', '-----'), ('Titular', 'Titular'), ('Adiestrado', 'Adiestrado'), ('Instructor', 'Instructor')], default='-----', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Admin', 'Admin')], default='1Usuario', max_length=7),
        ),
    ]
