# Generated by Django 3.2.9 on 2022-01-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220103_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Admin', 'Admin')], default='Usuario', max_length=7),
        ),
    ]
