# Generated by Django 3.2.9 on 2022-01-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220105_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'perfiles'},
        ),
    ]
