# Generated by Django 3.2.9 on 2022-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_perfil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='hora',
            field=models.TimeField(),
        ),
    ]
