# Generated by Django 3.2.9 on 2022-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220106_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=9),
        ),
    ]
