# Generated by Django 3.2.9 on 2022-01-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_denuncia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='fecha_asignada',
            field=models.DateField(null='True'),
            preserve_default='True',
        ),
    ]
