# Generated by Django 3.2.9 on 2022-01-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_denuncia_fecha_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='denuncia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.denuncia'),
        ),
    ]
