# Generated by Django 3.2.9 on 2022-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_expediente_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fecha',
            field=models.DateField(),
        ),
    ]
