# Generated by Django 3.2.9 on 2022-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_expediente_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name_plural': 'comisiones'},
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='area',
            field=models.CharField(max_length=50),
        ),
    ]
