# Generated by Django 3.2.9 on 2022-01-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220106_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='otros',
            field=models.CharField(max_length=300, null='True'),
        ),
    ]
