# Generated by Django 3.2.9 on 2022-01-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_comision_otros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='comision_a',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='comision_a',
            field=models.ManyToManyField(null=True, to='core.comision'),
        ),
    ]
