# Generated by Django 3.2.9 on 2022-01-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220107_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='comision_a',
            field=models.ManyToManyField(to='core.comision'),
        ),
    ]
